### ISSUE TITLE
Separare modele

### ISSUE THREAD

**Issue by DragosSHD** [MateiVolo05/Basketball-Nation#1]
https://github.com/MateiVolo05/Basketball-Nation/blob/2dc1af559299e88a3dc732ea596cc0a06d56ce4a/models/Article.js#L31

Initial am crezut ca nu exista un model pentru category, atunci cand am vazut ca fisierul se numeste Article.js. Doar pentru a putea fi mai usor de gasit, ai putea pune un nume mai generic fisierului (ex: models.js) sau sa separi cele doua modele in fisiere speparate (ex: article.js si category.js).

**Comment by MateiVolo05** [comment]
Uitasem sa i schimb numele
