### ISSUE TITLE
Conditie 404

### ISSUE THREAD

**Issue by DragosSHD** [MateiVolo05/Basketball-Nation#2]
https://github.com/MateiVolo05/Basketball-Nation/blob/2dc1af559299e88a3dc732ea596cc0a06d56ce4a/routes/article.js#L17

Aici ai putea adauga o conditie ca sa verifici daca id-ul solicitat exista in baza de date si, in caz contrar, sa randezi o pagina cu eroare 404 sau doar raspuns cu status 404.

**Comment by MateiVolo05** [comment]
e facut. categories nu e bagat in try catch ca sa l faca din prima. Daca nu sunt category la dropdown afiseaza doar optiunea home
